/*
 **  Data model initialization
 */

// Declare enum for fruit types
const Type = Object.freeze({
  MELON: "Melon",
  POME: "Pome",
  BERRY: "Berry",
  TROPICAL: "Tropical",
  STONE: "Stone",
  CITRUS: "Citrus",
  NUT: "Nut",
});

// Declare enum for Countries
const CountriesCode = Object.freeze({
  AE: "United Arab Emirates",
  AR: "Argentina",
  AT: "Austria",
  AU: "Australia",
  BE: "Belgium",
  BG: "Bulgaria",
  BR: "Brazil",
  CA: "Canada",
  CH: "Switzerland",
  CL: "Chile",
  CN: "China",
  CR: "Costa Rica",
  DE: "Germany",
  DK: "Denmark",
  EC: "Ecuador",
  EG: "Egypt",
  ES: "Spain",
  FI: "Finland",
  FJ: "Fiji",
  FR: "France",
  GB: "UK",
  GH: "Ghana",
  GR: "Greece",
  HK: "Hong Kong",
  HT: "Haiti",
  HU: "Hungary",
  ID: "Indonesia",
  IE: "Ireland",
  IL: "Israel",
  IN: "India",
  IQ: "Iraq",
  IR: "Iran",
  IS: "Iceland",
  IT: "Italy",
  JM: "Jamaica",
  JP: "Japan",
  KE: "Kenya",
  KH: "Cambodia",
  KR: "Korea",
  KW: "Kuwait",
  LK: "Sri Lanka",
  MM: "Myanmar",
  MU: "Mauritius",
  MX: "Mexico",
  MY: "Malaysia",
  NG: "Nigeria",
  NO: "Norway",
  NP: "Nepal",
  NZ: "New Zealand",
  PA: "Panama",
  PE: "Peru",
  PG: "Papua New Guinea",
  PH: "Phillipines",
  PK: "Pakistan",
  PL: "Poland",
  PT: "Portugal",
  QA: "Qatar",
  RO: "Romania",
  RU: "Russia",
  RW: "Rwanda",
  SA: "Saudi Arabia",
  SE: "Sweden",
  SG: "Singapore",
  SK: "Slovakia",
  SS: "South Sudan",
  SV: "El Salador",
  TH: "Thailand",
  TR: "Turkey",
  TW: "Taiwan",
  TZ: "Tanzania",
  UA: "Ukraine",
  UG: "Uganda",
  US: "USA",
  UY: "Uruguay",
  VE: "Venezuela",
  VN: "Vietnam",
  YE: "Yemen",
  ZA: "South Africa",
});

// Main fruit list
const fruits_original = [
  {
    id: "apple-001",
    name: "Fuji Apple",
    description:
      "Famous apple from Japan, it is large, with vibrant colors, usually red and yellow stripes, the flesh is crisp, and the taste is sweet.",
    rate: 5,
    type: Type.POME,
    weight: "1 lb",
    container: "Cartoon",
    country_of_origin: CountriesCode.JP,
    price: 150,
    image_1: "images/FujiApple-image-1-270X280.png",
    image_2: "images/FujiApple-image-2-270X280.png",
    image_3: "images/FujiApple-image-3-270X280.png",
    image_4: "images/FujiApple-image-4-169X152.png",
    image_5: "images/FujiApple-image-5-169X152.png",
    image_6: "images/FujiApple-image-6-169X152.png",
    image_7: "images/FujiApple-image-7-108X100.png",
    image_8: "images/FujiApple-image-8-146X132.png",
  },
  {
    id: "apple-002",
    name: "Granny Smith Apple",
    description:
      "Famous apple from Australia, it is a crisp, green variety of apple known for its tart flavor and firm texture. ",
    rate: 5,
    type: Type.POME,
    weight: "1 lb",
    container: "Cartoon",
    country_of_origin: CountriesCode.AT,
    price: 110,
    image_1: "images/GrannySmith-image-1-270X280.png",
    image_2: "images/GrannySmith-image-2-270X280.png",
    image_3: "images/GrannySmith-image-3-270X280.png",
    image_4: "images/GrannySmith-image-4-169X152.png",
    image_5: "images/GrannySmith-image-5-169X152.png",
    image_6: "images/GrannySmith-image-6-169X152.png",
    image_7: "images/GrannySmith-image-7-108X100.png",
    image_8: "images/GrannySmith-image-8-146X132.png",
  },
  {
    id: "apple-003",
    name: "Red Delicious Apple",
    description:
      "Famous apple from USA, it is red, the flesh is soft, and the sweetness is rich.",
    rate: 5,
    type: Type.POME,
    weight: "1 lb",
    container: "Cartoon",
    country_of_origin: CountriesCode.US,
    price: 120,
    image_1: "images/RedDelicious-image-1-270X280.png",
    image_2: "images/RedDelicious-image-2-270X280.png",
    image_3: "images/RedDelicious-image-3-270X280.png",
    image_4: "images/RedDelicious-image-4-169X152.png",
    image_5: "images/RedDelicious-image-5-169X152.png",
    image_6: "images/RedDelicious-image-6-169X152.png",
    image_7: "images/RedDelicious-image-7-108X100.png",
    image_8: "images/RedDelicious-image-8-146X132.png",
  },
  {
    id: "pear-001",
    name: "Anjou Pear",
    description:
      "The Anjou Pear is grown in the U.S. (mainly in California and Oregon) and France.It is sizable, the rind is green or yellow, the pulp is juicy, and the taste is a combination of sweetness and tartness.",
    rate: 4,
    type: Type.POME,
    weight: "1 lb",
    container: "Cartoon",
    country_of_origin: CountriesCode.FR,
    price: 88,
    image_1: "images/AnjouPear-image-1-270X280.png",
    image_2: "images/AnjouPear-image-2-270X280.png",
    image_3: "images/AnjouPear-image-3-270X280.png",
    image_4: "images/AnjouPear-image-4-169X152.png",
    image_5: "images/AnjouPear-image-5-169X152.png",
    image_6: "images/AnjouPear-image-6-169X152.png",
    image_7: "images/AnjouPear-image-7-108X100.png",
    image_8: "images/AnjouPear-image-8-146X132.png",
  },
  {
    id: "pear-002",
    name: "Shinko Pear",
    description:
      "The origin of the Shinko Pear is Japan, with widespread cultivation in the country's prominent pear-producing regions like Nagano and Yamanashi Prefectures. It is large, the rind is yellow, the flesh is crisp but delicate, and the flavor is sweetly aromatic.",
    rate: 5,
    type: Type.POME,
    weight: "1 lb",
    container: "Cartoon",
    country_of_origin: CountriesCode.JP,
    price: 188,
    image_1: "images/ShinkoPear-image-1-270X280.png",
    image_2: "images/ShinkoPear-image-2-270X280.png",
    image_3: "images/ShinkoPear-image-3-270X280.png",
    image_4: "images/ShinkoPear-image-4-169X152.png",
    image_5: "images/ShinkoPear-image-5-169X152.png",
    image_6: "images/ShinkoPear-image-6-169X152.png",
    image_7: "images/ShinkoPear-image-7-108X100.png",
    image_8: "images/ShinkoPear-image-8-146X132.png",
  },
  {
    id: "banana-001",
    name: "Cavendish Banana",
    description:
      "Famous banana from Phillipines. The skin is smooth, the color is a vibrant yellow, the flesh is soft, the taste is sweet, and it is seedless.",
    rate: 4,
    type: Type.TROPICAL,
    weight: "1 lb",
    container: "Cartoon",
    country_of_origin: CountriesCode.PH,
    price: 50,
    image_1: "images/CavendishBanana-image-1-270X280.png",
    image_2: "images/CavendishBanana-image-2-270X280.png",
    image_3: "images/CavendishBanana-image-3-270X280.png",
    image_4: "images/CavendishBanana-image-4-169X152.png",
    image_5: "images/CavendishBanana-image-5-169X152.png",
    image_6: "images/CavendishBanana-image-6-169X152.png",
    image_7: "images/CavendishBanana-image-7-108X100.png",
    image_8: "images/CavendishBanana-image-8-146X132.png",
  },
  {
    id: "banana-002",
    name: "Apple Banana",
    description:
      "Famous banana from Panama. It is small and round, the skin is yellow, the taste is sweet with a slight acidity, and it has a fragrance similar to apples.",
    rate: 4,
    type: Type.TROPICAL,
    weight: "1 lb",
    container: "Cartoon",
    country_of_origin: CountriesCode.PA,
    price: 60,
    image_1: "images/AppleBanana-image-1-270X280.png",
    image_2: "images/AppleBanana-image-2-270X280.png",
    image_3: "images/AppleBanana-image-3-270X280.png",
    image_4: "images/AppleBanana-image-4-169X152.png",
    image_5: "images/AppleBanana-image-5-169X152.png",
    image_6: "images/AppleBanana-image-6-169X152.png",
    image_7: "images/AppleBanana-image-7-108X100.png",
    image_8: "images/AppleBanana-image-8-146X132.png",
  },
  {
    id: "banana-003",
    name: "Red Banana",
    description:
      "Famous banana from Southeast Asia. The skin is red or purple-red, the flesh is relatively sweet and has a dense texture, and the size is smaller.",
    rate: 3,
    type: Type.TROPICAL,
    weight: "1 lb",
    container: "Cartoon",
    country_of_origin: CountriesCode.TH,
    price: 60,
    image_1: "images/RedBanana-image-1-270X280.png",
    image_2: "images/RedBanana-image-2-270X280.png",
    image_3: "images/RedBanana-image-3-270X280.png",
    image_4: "images/RedBanana-image-4-169X152.png",
    image_5: "images/RedBanana-image-5-169X152.png",
    image_6: "images/RedBanana-image-6-169X152.png",
    image_7: "images/RedBanana-image-7-108X100.png",
    image_8: "images/RedBanana-image-8-146X132.png",
  },
  {
    id: "rambutan-001",
    name: "Rambutan",
    description:
      "The primary origins are the West Java and North Sumatra regions of Indonesia. The rambutan grown here have a delicate, juicy flesh with a mildly tart-sweet flavor profile. Their skin is typically a reddish hue and features longer spines, while the overall fragrance is rich and aromatic.",
    rate: 4,
    type: Type.TROPICAL,
    weight: "1 lb",
    container: "Cartoon",
    country_of_origin: CountriesCode.ID,
    price: 120,
    image_1: "images/Rambutan-image-1-270X280.png",
    image_2: "images/Rambutan-image-2-270X280.png",
    image_3: "images/Rambutan-image-3-270X280.png",
    image_4: "images/Rambutan-image-4-169X152.png",
    image_5: "images/Rambutan-image-5-169X152.png",
    image_6: "images/Rambutan-image-6-169X152.png",
    image_7: "images/Rambutan-image-7-108X100.png",
    image_8: "images/Rambutan-image-8-146X132.png",
  },
  {
    id: "pineapple-001",
    name: "Golden Diamond Pineapple",
    description:
      "The main pineapple varieties cultivated in Taiwan include the Crown Pineapple and the Golden Diamond Pineapple. These pineapples have a golden yellow exterior with a distinct pineapple-like crown. The fruit shape is round and the coloration is vibrant. The flesh is juicy and tender, with a high sugar content, moderate acidity, and an excellent, delectable taste. They are particularly suitable for fresh consumption as a fruit. Pineapples are rich in vitamin C, fiber, and various antioxidants, which help boost the immune system and aid digestion.",
    rate: 5,
    type: Type.TROPICAL,
    weight: "1 lb",
    container: "Cartoon",
    country_of_origin: CountriesCode.TW,
    price: 180,
    image_1: "images/Pineapple-image-1-270X280.png",
    image_2: "images/Pineapple-image-2-270X280.png",
    image_3: "images/Pineapple-image-3-270X280.png",
    image_4: "images/Pineapple-image-4-169X152.png",
    image_5: "images/Pineapple-image-5-169X152.png",
    image_6: "images/Pineapple-image-6-169X152.png",
    image_7: "images/Pineapple-image-7-108X100.png",
    image_8: "images/Pineapple-image-8-146X132.png",
  },
  {
    id: "mango-001",
    name: "Irwin Mango",
    description:
      "The Irwin mango has a smooth skin that transitions from green to a vibrant yellow or orange hue upon ripening, often with reddish speckles. The flesh is a golden yellow color, with a soft, low-fiber texture and a smooth, creamy mouthfeel. The flavor is sweetly delicious, with a subtle acidity and robust aroma. It has a relatively high sugar content, making it a highly popular variety. The Ataúlfo mango is rich in vitamins A and C, as well as dietary fiber, which helps boost the immune system, aid digestion, and improve skin health.",
    rate: 5,
    type: Type.TROPICAL,
    weight: "1 lb",
    container: "Cartoon",
    country_of_origin: CountriesCode.TW,
    price: 280,
    image_1: "images/IrwinMango-image-1-270X280.png",
    image_2: "images/IrwinMango-image-2-270X280.png",
    image_3: "images/IrwinMango-image-3-270X280.png",
    image_4: "images/IrwinMango-image-4-169X152.png",
    image_5: "images/IrwinMango-image-5-169X152.png",
    image_6: "images/IrwinMango-image-6-169X152.png",
    image_7: "images/IrwinMango-image-7-108X100.png",
    image_8: "images/IrwinMango-image-8-146X132.png",
  },
  {
    id: "grape-001",
    name: "Red Globe Grapes",
    description:
      "Famous grapes from the United States (California), it is a large fruit, bright red in color, the flesh is juicy, the taste is sweet, and although it has seeds, they usually do not affect the eating experience.",
    rate: 4,
    type: Type.BERRY,
    weight: "1 lb",
    container: "Plastic",
    country_of_origin: CountriesCode.US,
    price: 380,
    image_1: "images/RedGlobe-image-1-270X280.png",
    image_2: "images/RedGlobe-image-2-270X280.png",
    image_3: "images/RedGlobe-image-3-270X280.png",
    image_4: "images/RedGlobe-image-4-169X152.png",
    image_5: "images/RedGlobe-image-5-169X152.png",
    image_6: "images/RedGlobe-image-6-169X152.png",
    image_7: "images/RedGlobe-image-7-108X100.png",
    image_8: "images/RedGlobe-image-8-146X132.png",
  },
  {
    id: "grape-002",
    name: "Sultana Grapes",
    description:
      "Famous grapes from the United States (California), it is green and seedless, the skin is smooth, the flesh is crisp and tender, the taste is sweet, and it is well-hydrated.",
    rate: 4,
    type: Type.BERRY,
    weight: "1 lb",
    container: "Plastic",
    country_of_origin: CountriesCode.US,
    price: 300,
    image_1: "images/Sultana-image-1-270X280.png",
    image_2: "images/Sultana-image-2-270X280.png",
    image_3: "images/Sultana-image-3-270X280.png",
    image_4: "images/Sultana-image-4-169X152.png",
    image_5: "images/Sultana-image-5-169X152.png",
    image_6: "images/Sultana-image-6-169X152.png",
    image_7: "images/Sultana-image-7-108X100.png",
    image_8: "images/Sultana-image-8-146X132.png",
  },
  {
    id: "grape-003",
    name: "Kyoho Grapes",
    description:
      "Famous grapes from Japan, it is large, the color is deep purple, the skin is thin, the flesh is juicy, the taste is sweet, and it has a rich, aromatic fragrance.",
    rate: 5,
    type: Type.BERRY,
    weight: "1 lb",
    container: "Plastic",
    country_of_origin: CountriesCode.JP,
    price: 580,
    image_1: "images/Kyoho-image-1-270X280.png",
    image_2: "images/Kyoho-image-2-270X280.png",
    image_3: "images/Kyoho-image-3-270X280.png",
    image_4: "images/Kyoho-image-4-169X152.png",
    image_5: "images/Kyoho-image-5-169X152.png",
    image_6: "images/Kyoho-image-6-169X152.png",
    image_7: "images/Kyoho-image-7-108X100.png",
    image_8: "images/Kyoho-image-8-146X132.png",
  },
  {
    id: "strawberry-001",
    name: "Akihime Strawberry",
    description:
      "Famous strawberry from Japan, it is large, the exterior is bright red, the flesh is firm, the taste is sweet, and it has a rich, aromatic fragrance.",
    rate: 5,
    type: Type.BERRY,
    weight: "1 lb",
    container: "Plastic",
    country_of_origin: CountriesCode.JP,
    price: 680,
    image_1: "images/Akihime-image-1-270X280.png",
    image_2: "images/Akihime-image-2-270X280.png",
    image_3: "images/Akihime-image-3-270X280.png",
    image_4: "images/Akihime-image-4-169X152.png",
    image_5: "images/Akihime-image-5-169X152.png",
    image_6: "images/Akihime-image-6-169X152.png",
    image_7: "images/Akihime-image-7-108X100.png",
    image_8: "images/Akihime-image-8-146X132.png",
  },
  {
    id: "strawberry-002",
    name: "Albino Strawberry",
    description:
      "Famous strawberry from Japan, it is medium-sized, the exterior is white, the flesh is juicy and sweet, the appearance is distinctive, and it is usually more storable.",
    rate: 5,
    type: Type.BERRY,
    weight: "1 lb",
    container: "Plastic",
    country_of_origin: CountriesCode.JP,
    price: 880,
    image_1: "images/Albino-image-1-270X280.png",
    image_2: "images/Albino-image-2-270X280.png",
    image_3: "images/Albino-image-3-270X280.png",
    image_4: "images/Albino-image-4-169X152.png",
    image_5: "images/Albino-image-5-169X152.png",
    image_6: "images/Albino-image-6-169X152.png",
    image_7: "images/Albino-image-7-108X100.png",
    image_8: "images/Albino-image-8-146X132.png",
  },
  {
    id: "strawberry-003",
    name: "Pink Strawberry",
    description:
      "Famous strawberry from Japan, it is medium-sized, the exterior is a light pink color, the flesh is firm, the taste is sweet, and it has a rich, aromatic fragrance.",
    rate: 5,
    type: Type.BERRY,
    weight: "1 lb",
    container: "Plastic",
    country_of_origin: CountriesCode.JP,
    price: 880,
    image_1: "images/Pinkstrawberry-image-1-270X280.png",
    image_2: "images/Pinkstrawberry-image-2-270X280.png",
    image_3: "images/Pinkstrawberry-image-3-270X280.png",
    image_4: "images/Pinkstrawberry-image-4-169X152.png",
    image_5: "images/Pinkstrawberry-image-5-169X152.png",
    image_6: "images/Pinkstrawberry-image-6-169X152.png",
    image_7: "images/Pinkstrawberry-image-7-108X100.png",
    image_8: "images/Pinkstrawberry-image-8-146X132.png",
  },
  {
    id: "blueberry-001",
    name: "Blueberry",
    description:
      "The United States is the world's largest producer of blueberries, particularly in the states of Michigan, Washington, and Oregon. The main types are Highbush Blueberry and Lowbush Blueberry.",
    rate: 4,
    type: Type.BERRY,
    weight: "1 lb",
    container: "Plastic",
    country_of_origin: CountriesCode.US,
    price: 180,
    image_1: "images/Blueberry-image-1-270X280.png",
    image_2: "images/Blueberry-image-2-270X280.png",
    image_3: "images/Blueberry-image-3-270X280.png",
    image_4: "images/Blueberry-image-4-169X152.png",
    image_5: "images/Blueberry-image-5-169X152.png",
    image_6: "images/Blueberry-image-6-169X152.png",
    image_7: "images/Blueberry-image-7-108X100.png",
    image_8: "images/Blueberry-image-8-146X132.png",
  },
  {
    id: "orange-001",
    name: "Orange",
    description:
      "The United States is the world's largest producer of orange, particularly in the states of California and Florida. California's oranges are known for the Washington navel and Valencia varieties, while Florida is renowned for its production of juice oranges.",
    rate: 4,
    type: Type.CITRUS,
    weight: "1 lb",
    container: "Cartoon",
    country_of_origin: CountriesCode.US,
    price: 98,
    image_1: "images/Orange-image-1-270X280.png",
    image_2: "images/Orange-image-2-270X280.png",
    image_3: "images/Orange-image-3-270X280.png",
    image_4: "images/Orange-image-4-169X152.png",
    image_5: "images/Orange-image-5-169X152.png",
    image_6: "images/Orange-image-6-169X152.png",
    image_7: "images/Orange-image-7-108X100.png",
    image_8: "images/Orange-image-8-146X132.png",
  },
  {
    id: "lemon-001",
    name: "Lemon",
    description:
      "The main producing regions for lemons are the provinces of Santa Fe and Córdoba in Argentina. The lemon has a bright, yellowish-orange color reminiscent of lemons, and it emits a fragrant, aromatic scent. It is considered a highly nutritious type of produce.",
    rate: 3,
    type: Type.CITRUS,
    weight: "1 lb",
    container: "Cartoon",
    country_of_origin: CountriesCode.AR,
    price: 98,
    image_1: "images/Lemon-image-1-270X280.png",
    image_2: "images/Lemon-image-2-270X280.png",
    image_3: "images/Lemon-image-3-270X280.png",
    image_4: "images/Lemon-image-4-169X152.png",
    image_5: "images/Lemon-image-5-169X152.png",
    image_6: "images/Lemon-image-6-169X152.png",
    image_7: "images/Lemon-image-7-108X100.png",
    image_8: "images/Lemon-image-8-146X132.png",
  },
  {
    id: "mandarin-001",
    name: "Ehime Mikan",
    description:
      "The key production areas for Japanese oranges are the prefectures of Hiroshima and Ehime. Japan boasts a wide variety of mandarin cultivars, especially the Mikan, which are renowned for their round shape, thin skin, high sugar content, and widespread popularity. These oranges generally ripen in the winter months and possess an exceptional taste.",
    rate: 5,
    type: Type.CITRUS,
    weight: "1 lb",
    container: "Cartoon",
    country_of_origin: CountriesCode.JP,
    price: 288,
    image_1: "images/EhimeMikan-image-1-270X280.png",
    image_2: "images/EhimeMikan-image-2-270X280.png",
    image_3: "images/EhimeMikan-image-3-270X280.png",
    image_4: "images/EhimeMikan-image-4-169X152.png",
    image_5: "images/EhimeMikan-image-5-169X152.png",
    image_6: "images/EhimeMikan-image-6-169X152.png",
    image_7: "images/EhimeMikan-image-7-108X100.png",
    image_8: "images/EhimeMikan-image-8-146X132.png",
  },
];

const pikachus = [
  "./images/peka_farfetchd.png",
  "./images/peka_jigglypuff.png",
  "./images/peka_magikarp.png",
  "./images/peka_meowth.png",
  "./images/peka_pansage.png",
  "./images/peka_pikachu.png",
  "./images/peka_psyduck.png",
  "./images/peka_snorlax.png",
  "./images/peka_保母蟲.png",
];

const fruit_comments = [
  {
    id: 1,
    fruit_id: "grape-003",
    image: "./images/peka_pansage.png",
    name: "John Doe",
    date: "Nov 27, 2024",
    rating: 5,
    comment:
      "The product you delivered me has surpassed all my expectations. The item is one of the best, all-purpose items ever crafted. I love everything about my purchase. Reliable, secure, quirky, easy to clean in and out.",
  },
];

const article_comments = [
  {
    id: 1,
    name: "John Doe",
    image: "./images/peka_pansage.png",
    date: "Nov 27, 2024",
    content:
      "You have to always continue to strive no matter how hard things get, no matter how troubled you feel. No matter how tough things get, no matter how many times you lose, you keep trying to win.",
  },
];

const delivery_pass = [
  {
    id: 1,
    name: "VIP Pass",
    type: "pass",
    description: "1 month",
    price: 169,
    image_7: "images/VipPass-image-7-108X100.png",
    image_8: "images/VipPass-image-8-146X132.png",
  },
  {
    id: 2,
    name: "Silver Pass",
    type: "pass",
    description: "3 months",
    price: 299,
    image_7: "images/SilverPass-image-7-108X100.png",
    image_8: "images/SilverPass-image-8-146X132.png",
  },
  {
    id: 3,
    name: "Gold Pass",
    type: "pass",
    description: "6 months",
    price: 499,
    image_7: "images/GoldPass-image-7-108X100.png",
    image_8: "images/GoldPass-image-8-146X132.png",
  },
];

const blog_posts = [
  {
    id: 1,
    author: "Ann Smith",
    number_of_comments: 14,
    avator: "./images/peka_magikarp.png",
    date: "Mar 17, 2024",
    category: "News Philosophy Leisure",
    image_1: "images/post-1-image-1-370X267.JPG",
    image_2: "images/post-1-image-2-769X431.jpg",
    image_3: "images/post-1-image-3-232X138.jpg",
    title: "How the 'Japanese Mikan Effect' Changes People",
    text_1:
      "The Japanese Mikan Effect is not just a tale of a fruit—it is a metaphor for the delicate balance between control and chaos, a reminder that in embracing the unknown, we find the seeds of our greatest potential.",
    text_2:
      "Much like the Black Swan, the Japanese Mikan teaches us that our lives are shaped by rare and unexpected events. These events, often dismissed as outliers, can have a monumental impact on our personal and collective narratives. The farmers who tend to these orchards understand this well; their wisdom is steeped in the acceptance of the unknown and the embrace of life's inherent volatility.",
    text_3:
      "The mikan's journey from seedling to fruit mirrors the unpredictable twists and turns of life. Despite meticulous care and favorable conditions, the yield of the mikan harvest can never be precisely predicted. The slightest fluctuation in weather, an unforeseen pest invasion, or an unexpected market shift can transform a bountiful season into one of scarcity. It is within these uncertainties that the true essence of the 'Japanese Mikan Effect' emerges.",
  },
  {
    id: 2,
    author: "Kate Williams",
    number_of_comments: 33,
    avator: "./images/peka_jigglypuff.png",
    date: "Mar 31, 2024",
    category: "Recipes Fitness Organic",
    image_1: "images/post-2-image-1-370X267.JPG",
    image_2: "images/post-2-image-2-769X431.jpg",
    image_3: "images/post-2-image-3-232X138.jpg",
    title: "Every Breakfast Like a King Choices for a Healthier, Happier You",
    text_1:
      "Handy 10 minute recipes when you need to pull a quick meal or snack together right away. Whether that's a pasta dish, omelette or a quick sandwich, we have some ideas below - even a Belgian Waffle Stack!",
    text_2:
      "Breakfast like a king with this delicious waffle stack with Greek-style yogurt and fresh berries",
    text_3:
      "We share your passion for enjoying the most flavoursome, best quality food and drink and that’s why we have a team of culinary experts dedicated to bringing you the best. Whether it’s about growing, sourcing or skilful crafting of our products, we are all united in our dedication to sharing the greatest tasting food and drink with you and we guarantee every product has a distinct taste story…. ",
  },
  {
    id: 3,
    author: "Peter McMillan",
    number_of_comments: 26,
    avator: "./images/peka_snorlax.png",
    date: "Apr 23, 2024",
    category: "Guide Fitness Recipes",
    image_1: "images/post-3-image-1-370X267.JPG",
    image_2: "images/post-3-image-2-769X431.jpg",
    image_3: "images/post-3-image-3-232X138.jpg",
    title:
      "Love This Fruit Oatmeal Bowl, Mixing all the Different Fresh Fruits",
    text_1:
      "This Fruit Oatmeal Bowl is a perfect way to start your day with a burst of energy and a healthy dose of vitamins. It’s also a wonderful way to celebrate the season’s bounty, making each morning a little brighter and more delicious. Bon appétit!",
    text_2:
      "Take a moment to admire your culinary creation before diving in. The combination of creamy oatmeal and juicy, fresh fruits is sure to bring a smile to your face and a spring to your step.",
    text_3:
      "The humble oatmeal is transformed into a vibrant, fruit-filled masterpiece. This Fruit Oatmeal Bowl is not only a feast for the eyes but a symphony of flavors that will dance on your palate. Let’s dive into the world of fresh fruits and wholesome oats, shall we?",
  },
  {
    id: 4,
    author: "Ann Smith",
    number_of_comments: 17,
    avator: "./images/peka_magikarp.png",
    date: "May 08, 2024",
    category: "Philosophy Self-help Leisure",
    image_1: "images/post-4-image-1-370X267.png",
    image_2: "images/post-4-image-2-769X431.jpg",
    image_3: "images/post-4-image-3-232X138.png",
    title: "Our Soul also Needs 'Fruit for the Soul' to noursih and Flourish",
    text_1:
      "Our story begins with a simple truth: to truly flourish, we must first nourish our souls. Join me as we embark on this voyage through the garden of life, discovering the fruits that will sustain us, inspire us, and lead us to a life of fulfillment and joy.",
    text_2:
      "Imagine a garden, bathed in golden sunlight, where every plant and tree represents a facet of our spirit. In this garden, we find 'Fruit for the Soul' – those moments and experiences that enrich our lives and help us flourish. Just as a tree needs water, sunlight, and care to thrive, our souls require love, understanding, and hope to grow.",
    text_3:
      "In this journey, we will explore the myriad fruits that life offers, each one a beacon of light in times of darkness, a source of strength in moments of weakness. These fruits come in many forms – the kind words of a friend, the warm embrace of a loved one, the quiet reflection in nature's embrace, or the triumphant feeling of overcoming a challenge.",
  },
  {
    id: 5,
    author: "Kate Williams",
    number_of_comments: 22,
    avator: "./images/peka_jigglypuff.png",
    date: "May 25, 2024",
    category: "Recipes Guide Leisure",
    image_1: "images/post-5-image-1-370X267.JPG",
    image_2: "images/post-5-image-2-769X431.jpg",
    image_3: "images/post-5-image-3-232X138.jpg",
    title: "Top 5 Easy and Yummy Baby Fruits Recipes",
    text_1:
      "Welcoming a baby into your family brings endless joy, but also the challenge of providing nutritious and delicious meals. Introducing fruits into your little one's diet can be both exciting and daunting. Fear not! Here are five easy and yummy fruit recipes that will delight your baby’s taste buds and ensure they're getting all the essential nutrients.",
    text_2:
      "Introducing these fruit recipes to your baby's diet will ensure they receive a variety of flavors and essential nutrients. Remember to always consult with your pediatrician before introducing new foods to your baby. Enjoy the journey of discovering new tastes and textures with your little one!",
    text_3:
      "Banana and Avocado Mash <br> A creamy and nutrient-packed delight that's perfect for your baby's first tastes.<p>Ingredients:<br>- 1 ripe banana<br>- 1/2ripe avocado<p>Instructions:<br>1. Peel the banana and avocado.<br>2. Mash them together until smooth.<br>3. Serve fresh to your baby. Refrigerate leftovers for up to 24 hours.",
  },
  {
    id: 6,
    author: "Peter McMillan",
    number_of_comments: 14,
    avator: "./images/peka_snorlax.png",
    date: "Jun 04, 2024",
    category: "News Products Limited-Edition",
    image_1: "images/post-6-image-1-370X267.JPG",
    image_2: "images/post-6-image-2-769X431.jpg",
    image_3: "images/post-6-image-3-232X138.jpg",
    title: "Rare and Limited Edition Greater Bay Fruits(GBF) x Dior",
    text_1:
      "When it comes to gifting, nothing says luxury and exclusivity quite like the collaboration between Greater Bay Fruits(GBF) and the iconic British designer Kim Jones, who recently took the helm at Dior. The 2024-2025 men's collection, aptly named 'Joyful Wonderland', is a testament to the fusion of high fashion and gourmet indulgence.",
    text_2:
      "True to the nature of luxury collaborations, the GBF x Kim Jones collection is available in extremely limited quantities. This scarcity ensures that each piece is not only unique but also highly coveted by fashion enthusiasts and collectors alike.",
    text_3:
      "Perfect for:<p>- The fashion-forward friend who appreciates luxury and exclusivity.<br>- The gourmet lover who enjoys unique culinary experiences.<br>- The collector looking for rare and limited-edition items.<br>- The trendsetter who wants to stay ahead of the fashion curve.",
  },
];

/*
 **  End of Data model initialization
 */

/*
 **  Data setup
 */

// Store fruit list and initial index number for single product page into local storage.
localStorage.setItem("fruits", JSON.stringify(fruits_original));
localStorage.setItem("fruitIndex", "0");
localStorage.setItem("article_comments", JSON.stringify(article_comments));
localStorage.setItem("fruit_comments", JSON.stringify(fruit_comments));
localStorage.setItem("pikachus", JSON.stringify(pikachus));
localStorage.setItem("delivery_pass", JSON.stringify(delivery_pass));
localStorage.setItem("blog_posts", JSON.stringify(blog_posts));

/*
 **  End of data setup
 */
